[tool.poetry]
name        = 'rx_fitter'
version     = '0.0.1'
description = 'Framework used to handle fits to data and simulation'
readme      = 'README.md'
authors     = []
license     = ''
packages    = [
    { include = 'fitter'       , from = 'src' },
    { include = 'fitter_data'  , from = 'src' },
    { include = 'fitter_schema', from = 'src' },
]
include = ['src/fitter_data/**/*.yaml']

[tool.poetry.dependencies]
python         = '>=3.10,<3.13'
pdg            = '*'
omegaconf      = '*'
numpy          = '*'
seaborn        = '*'
mplhep         = '*'
matplotlib     = '*'
python-slugify = '*'
zfit           = '*'

[tool.poetry.scripts]
fit_rx_rare    = 'fitter_scripts.fit_rx_rare:main'
fit_rx_reso    = 'fitter_scripts.fit_rx_reso:main'
fit_grid       = 'fitter_scripts.fit_grid:main'
navigate_fits  = 'fitter_scripts.navigate_fits:main'
validate_cmb   = 'fitter_scripts.validate_cmb:main'
plot_toys      = 'fitter_scripts.plot_toys:main'
summarize_toys = 'fitter_scripts.summarize_toys:main'

[tool.poetry.group.dev.dependencies]
pytest = '*'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
