[project]
name        = 'fitter'
description = 'Framework used to handle fits to data and simulation'
version     = '0.0.1'
readme      = 'README.md'
dependencies= [
'omegaconf',
'data-manipulation-utilities']

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[tool.setuptools.package-data]
fitter_data=['**/*.yaml']
