[project]
name        = 'rx_fitter'
description = 'Framework used to handle fits to data and simulation'
version     = '0.0.1'
readme      = 'README.md'
dependencies= [
'omegaconf',
'numpy',
'mplhep',
'matplotlib',
'python-slugify',
'rx_data',
'rx_selection',
'data-manipulation-utilities']

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[tool.setuptools.package-data]
fitter_data=['**/*.yaml']

[project.scripts]
fit_rx_data ='fitter_scripts.fit_rx_data:main'
